# 指定服务的名称
dubbo:
  application:
    name: myProvider
  registry:
    address: zookeeper://192.168.9.133:2181
    timeout: 10000
    # 配置服务所使用的协议
    protocol:
      name: dubbo
      port: 8889
  scan:
    base-packages: com.bjsxt.springbootdubbo_provider.service.impl
